# Generated by Django 3.1.3 on 2020-12-19 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='node_details',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('board', models.TextField(blank=True)),
                ('has_camera', models.BooleanField()),
                ('last_active', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sensor_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('date_inserted', models.DateTimeField(auto_now=True)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.node_details')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
