# Generated by Django 3.1.3 on 2020-12-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_details',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
